# Student Configuration
# ==================
# Please change YOUR_NAME_HERE to your actual name
student_name: YOUR_NAME_HERE

# Course Configuration (pre-filled by professor)
# ============================================
course_name: python-intro-2024
server_url: http://localhost:8000 